import type { Service } from "../types";

export const DEFAULT_SERVICES: Service[] = [
  {
    id: "svc-1",
    name: "Shampoo",
    price: 10,
    color: "#7EB8D4",
    category: "single",
    phases: [],
    totalDurationMinutes: 15,
  },
  {
    id: "svc-2",
    name: "Shampoo/Style",
    price: 28,
    color: "#88C5A0",
    category: "single",
    phases: [],
    totalDurationMinutes: 30,
  },
  {
    id: "svc-3",
    name: "Shampoo/Haircut (no style)",
    price: 25,
    color: "#9DB8C5",
    category: "single",
    phases: [],
    totalDurationMinutes: 30,
  },
  {
    id: "svc-4",
    name: "Shampoo/Haircut/Style",
    price: 38,
    color: "#B5C4D4",
    category: "single",
    phases: [],
    totalDurationMinutes: 30,
  },
  {
    id: "svc-5",
    name: "Men's Haircut",
    price: 25,
    color: "#9ECEAD",
    category: "single",
    phases: [],
    totalDurationMinutes: 30,
  },
  {
    id: "svc-6",
    name: "Beard Trim",
    price: 10,
    color: "#C5B4A0",
    category: "single",
    phases: [],
    totalDurationMinutes: 15,
  },
  {
    id: "svc-7",
    name: "Perm",
    price: 65,
    color: "#D4A5B5",
    category: "multi",
    finishingLabel: "Finish",
    phases: [
      { name: "Base", durationMinutes: 45, phaseType: "active" },
      { name: "Processing", durationMinutes: 30, phaseType: "processing" },
      { name: "Finish", durationMinutes: 30, phaseType: "active" },
    ],
    totalDurationMinutes: 105,
  },
  {
    id: "svc-8",
    name: "Perm/Style",
    price: 75,
    color: "#C4A0C4",
    category: "multi",
    finishingLabel: "Style",
    phases: [
      { name: "Base", durationMinutes: 45, phaseType: "active" },
      { name: "Processing", durationMinutes: 30, phaseType: "processing" },
      { name: "Style", durationMinutes: 30, phaseType: "active" },
    ],
    totalDurationMinutes: 105,
  },
  {
    id: "svc-9",
    name: "Perm/Haircut/Style",
    price: 85,
    color: "#B8A0C4",
    category: "multi",
    finishingLabel: "Haircut/Style",
    phases: [
      { name: "Base", durationMinutes: 45, phaseType: "active" },
      { name: "Processing", durationMinutes: 30, phaseType: "processing" },
      { name: "Haircut/Style", durationMinutes: 30, phaseType: "active" },
    ],
    totalDurationMinutes: 105,
  },
  {
    id: "svc-10",
    name: "Color",
    price: 60,
    color: "#D4B88C",
    category: "multi",
    finishingLabel: "Finish",
    phases: [
      { name: "Base", durationMinutes: 30, phaseType: "active" },
      { name: "Processing", durationMinutes: 30, phaseType: "processing" },
      { name: "Finish", durationMinutes: 15, phaseType: "active" },
    ],
    totalDurationMinutes: 75,
  },
  {
    id: "svc-11",
    name: "Color/Style",
    price: 70,
    color: "#D4C88C",
    category: "multi",
    finishingLabel: "Style",
    phases: [
      { name: "Base", durationMinutes: 30, phaseType: "active" },
      { name: "Processing", durationMinutes: 30, phaseType: "processing" },
      { name: "Style", durationMinutes: 30, phaseType: "active" },
    ],
    totalDurationMinutes: 90,
  },
  {
    id: "svc-12",
    name: "Color/Haircut/Style",
    price: 80,
    color: "#D4D48C",
    category: "multi",
    finishingLabel: "Haircut/Style",
    phases: [
      { name: "Base", durationMinutes: 30, phaseType: "active" },
      { name: "Processing", durationMinutes: 30, phaseType: "processing" },
      { name: "Haircut/Style", durationMinutes: 30, phaseType: "active" },
    ],
    totalDurationMinutes: 90,
  },
  {
    id: "svc-13",
    name: "Facial Waxing",
    price: 10,
    color: "#C4C4A0",
    category: "single",
    phases: [],
    totalDurationMinutes: 15,
  },
];
