/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : Id,
  'startTime' : HHmm,
  'clientName' : string,
  'date' : ISODate,
  'durationMinutes' : bigint,
  'notes' : [] | [string],
  'serviceId' : Id,
  'phone' : [] | [string],
  'price' : number,
  'phases' : [] | [Array<PhaseInstance>],
}
export interface CreateAppointmentInput {
  'startTime' : HHmm,
  'clientName' : string,
  'date' : ISODate,
  'durationMinutes' : bigint,
  'notes' : [] | [string],
  'serviceId' : Id,
  'phone' : [] | [string],
  'price' : number,
  'phases' : [] | [Array<PhaseInstance>],
}
export interface CreateServiceInput {
  'name' : string,
  'isMultiPhase' : boolean,
  'colorHex' : string,
  'price' : number,
  'finishingLabel' : [] | [string],
  'phases' : Array<PhaseDef>,
}
export type HHmm = string;
export type ISODate = string;
export type Id = string;
export interface PhaseDef {
  'phaseLabel' : string,
  'durationMinutes' : bigint,
  'phaseType' : PhaseType,
}
export interface PhaseInstance {
  'phaseLabel' : string,
  'durationMinutes' : bigint,
  'phaseType' : PhaseType,
}
export type PhaseType = { 'active' : null } |
  { 'processing' : null };
export interface Service {
  'id' : Id,
  'name' : string,
  'isMultiPhase' : boolean,
  'colorHex' : string,
  'price' : number,
  'finishingLabel' : [] | [string],
  'phases' : Array<PhaseDef>,
}
export interface SettingsSnapshot {
  'workingHoursEnd' : HHmm,
  'startWeekOnMonday' : boolean,
  'workingHoursStart' : HHmm,
}
export interface UpdateAppointmentInput {
  'id' : Id,
  'startTime' : HHmm,
  'clientName' : string,
  'date' : ISODate,
  'durationMinutes' : bigint,
  'notes' : [] | [string],
  'serviceId' : Id,
  'phone' : [] | [string],
  'price' : number,
  'phases' : [] | [Array<PhaseInstance>],
}
export interface UpdateServiceInput {
  'id' : Id,
  'name' : string,
  'isMultiPhase' : boolean,
  'colorHex' : string,
  'price' : number,
  'finishingLabel' : [] | [string],
  'phases' : Array<PhaseDef>,
}
export interface UpdateSettingsInput {
  'workingHoursEnd' : HHmm,
  'startWeekOnMonday' : boolean,
  'workingHoursStart' : HHmm,
}
export interface _SERVICE {
  'createAppointment' : ActorMethod<[CreateAppointmentInput], Appointment>,
  'createService' : ActorMethod<[CreateServiceInput], Service>,
  'deleteAppointment' : ActorMethod<[Id], boolean>,
  'deleteService' : ActorMethod<[Id], boolean>,
  'getAppointment' : ActorMethod<[Id], [] | [Appointment]>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentsByClient' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByDateRange' : ActorMethod<
    [ISODate, ISODate],
    Array<Appointment>
  >,
  'getClientNames' : ActorMethod<[], Array<string>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSettings' : ActorMethod<[], SettingsSnapshot>,
  'updateAppointment' : ActorMethod<
    [UpdateAppointmentInput],
    [] | [Appointment]
  >,
  'updateService' : ActorMethod<[UpdateServiceInput], [] | [Service]>,
  'updateSettings' : ActorMethod<[UpdateSettingsInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];