/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HHmm = IDL.Text;
export const ISODate = IDL.Text;
export const Id = IDL.Text;
export const PhaseType = IDL.Variant({
  'active' : IDL.Null,
  'processing' : IDL.Null,
});
export const PhaseInstance = IDL.Record({
  'phaseLabel' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'phaseType' : PhaseType,
});
export const CreateAppointmentInput = IDL.Record({
  'startTime' : HHmm,
  'clientName' : IDL.Text,
  'date' : ISODate,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : Id,
  'phone' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
  'phases' : IDL.Opt(IDL.Vec(PhaseInstance)),
});
export const Appointment = IDL.Record({
  'id' : Id,
  'startTime' : HHmm,
  'clientName' : IDL.Text,
  'date' : ISODate,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : Id,
  'phone' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
  'phases' : IDL.Opt(IDL.Vec(PhaseInstance)),
});
export const PhaseDef = IDL.Record({
  'phaseLabel' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'phaseType' : PhaseType,
});
export const CreateServiceInput = IDL.Record({
  'name' : IDL.Text,
  'isMultiPhase' : IDL.Bool,
  'colorHex' : IDL.Text,
  'price' : IDL.Float64,
  'finishingLabel' : IDL.Opt(IDL.Text),
  'phases' : IDL.Vec(PhaseDef),
});
export const Service = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'isMultiPhase' : IDL.Bool,
  'colorHex' : IDL.Text,
  'price' : IDL.Float64,
  'finishingLabel' : IDL.Opt(IDL.Text),
  'phases' : IDL.Vec(PhaseDef),
});
export const SettingsSnapshot = IDL.Record({
  'workingHoursEnd' : HHmm,
  'startWeekOnMonday' : IDL.Bool,
  'workingHoursStart' : HHmm,
});
export const UpdateAppointmentInput = IDL.Record({
  'id' : Id,
  'startTime' : HHmm,
  'clientName' : IDL.Text,
  'date' : ISODate,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'serviceId' : Id,
  'phone' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
  'phases' : IDL.Opt(IDL.Vec(PhaseInstance)),
});
export const UpdateServiceInput = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'isMultiPhase' : IDL.Bool,
  'colorHex' : IDL.Text,
  'price' : IDL.Float64,
  'finishingLabel' : IDL.Opt(IDL.Text),
  'phases' : IDL.Vec(PhaseDef),
});
export const UpdateSettingsInput = IDL.Record({
  'workingHoursEnd' : HHmm,
  'startWeekOnMonday' : IDL.Bool,
  'workingHoursStart' : HHmm,
});

export const idlService = IDL.Service({
  'createAppointment' : IDL.Func([CreateAppointmentInput], [Appointment], []),
  'createService' : IDL.Func([CreateServiceInput], [Service], []),
  'deleteAppointment' : IDL.Func([Id], [IDL.Bool], []),
  'deleteService' : IDL.Func([Id], [IDL.Bool], []),
  'getAppointment' : IDL.Func([Id], [IDL.Opt(Appointment)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentsByClient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByDateRange' : IDL.Func(
      [ISODate, ISODate],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getClientNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getSettings' : IDL.Func([], [SettingsSnapshot], ['query']),
  'updateAppointment' : IDL.Func(
      [UpdateAppointmentInput],
      [IDL.Opt(Appointment)],
      [],
    ),
  'updateService' : IDL.Func([UpdateServiceInput], [IDL.Opt(Service)], []),
  'updateSettings' : IDL.Func([UpdateSettingsInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HHmm = IDL.Text;
  const ISODate = IDL.Text;
  const Id = IDL.Text;
  const PhaseType = IDL.Variant({
    'active' : IDL.Null,
    'processing' : IDL.Null,
  });
  const PhaseInstance = IDL.Record({
    'phaseLabel' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'phaseType' : PhaseType,
  });
  const CreateAppointmentInput = IDL.Record({
    'startTime' : HHmm,
    'clientName' : IDL.Text,
    'date' : ISODate,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : Id,
    'phone' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
    'phases' : IDL.Opt(IDL.Vec(PhaseInstance)),
  });
  const Appointment = IDL.Record({
    'id' : Id,
    'startTime' : HHmm,
    'clientName' : IDL.Text,
    'date' : ISODate,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : Id,
    'phone' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
    'phases' : IDL.Opt(IDL.Vec(PhaseInstance)),
  });
  const PhaseDef = IDL.Record({
    'phaseLabel' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'phaseType' : PhaseType,
  });
  const CreateServiceInput = IDL.Record({
    'name' : IDL.Text,
    'isMultiPhase' : IDL.Bool,
    'colorHex' : IDL.Text,
    'price' : IDL.Float64,
    'finishingLabel' : IDL.Opt(IDL.Text),
    'phases' : IDL.Vec(PhaseDef),
  });
  const Service = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'isMultiPhase' : IDL.Bool,
    'colorHex' : IDL.Text,
    'price' : IDL.Float64,
    'finishingLabel' : IDL.Opt(IDL.Text),
    'phases' : IDL.Vec(PhaseDef),
  });
  const SettingsSnapshot = IDL.Record({
    'workingHoursEnd' : HHmm,
    'startWeekOnMonday' : IDL.Bool,
    'workingHoursStart' : HHmm,
  });
  const UpdateAppointmentInput = IDL.Record({
    'id' : Id,
    'startTime' : HHmm,
    'clientName' : IDL.Text,
    'date' : ISODate,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'serviceId' : Id,
    'phone' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
    'phases' : IDL.Opt(IDL.Vec(PhaseInstance)),
  });
  const UpdateServiceInput = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'isMultiPhase' : IDL.Bool,
    'colorHex' : IDL.Text,
    'price' : IDL.Float64,
    'finishingLabel' : IDL.Opt(IDL.Text),
    'phases' : IDL.Vec(PhaseDef),
  });
  const UpdateSettingsInput = IDL.Record({
    'workingHoursEnd' : HHmm,
    'startWeekOnMonday' : IDL.Bool,
    'workingHoursStart' : HHmm,
  });
  
  return IDL.Service({
    'createAppointment' : IDL.Func([CreateAppointmentInput], [Appointment], []),
    'createService' : IDL.Func([CreateServiceInput], [Service], []),
    'deleteAppointment' : IDL.Func([Id], [IDL.Bool], []),
    'deleteService' : IDL.Func([Id], [IDL.Bool], []),
    'getAppointment' : IDL.Func([Id], [IDL.Opt(Appointment)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentsByClient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByDateRange' : IDL.Func(
        [ISODate, ISODate],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getClientNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getSettings' : IDL.Func([], [SettingsSnapshot], ['query']),
    'updateAppointment' : IDL.Func(
        [UpdateAppointmentInput],
        [IDL.Opt(Appointment)],
        [],
      ),
    'updateService' : IDL.Func([UpdateServiceInput], [IDL.Opt(Service)], []),
    'updateSettings' : IDL.Func([UpdateSettingsInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };