/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateServiceInput {
    id: Id;
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel?: string;
    phases: Array<PhaseDef>;
}
export type HHmm = string;
export interface Service {
    id: Id;
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel?: string;
    phases: Array<PhaseDef>;
}
export interface SettingsSnapshot {
    workingHoursEnd: HHmm;
    startWeekOnMonday: boolean;
    workingHoursStart: HHmm;
}
export interface PhaseInstance {
    phaseLabel: string;
    durationMinutes: bigint;
    phaseType: PhaseType;
}
export interface PhaseDef {
    phaseLabel: string;
    durationMinutes: bigint;
    phaseType: PhaseType;
}
export interface CreateServiceInput {
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel?: string;
    phases: Array<PhaseDef>;
}
export interface UpdateAppointmentInput {
    id: Id;
    startTime: HHmm;
    clientName: string;
    date: ISODate;
    durationMinutes: bigint;
    notes?: string;
    serviceId: Id;
    phone?: string;
    price: number;
    phases?: Array<PhaseInstance>;
}
export type ISODate = string;
export interface UpdateSettingsInput {
    workingHoursEnd: HHmm;
    startWeekOnMonday: boolean;
    workingHoursStart: HHmm;
}
export interface CreateAppointmentInput {
    startTime: HHmm;
    clientName: string;
    date: ISODate;
    durationMinutes: bigint;
    notes?: string;
    serviceId: Id;
    phone?: string;
    price: number;
    phases?: Array<PhaseInstance>;
}
export type Id = string;
export interface Appointment {
    id: Id;
    startTime: HHmm;
    clientName: string;
    date: ISODate;
    durationMinutes: bigint;
    notes?: string;
    serviceId: Id;
    phone?: string;
    price: number;
    phases?: Array<PhaseInstance>;
}
export enum PhaseType {
    active = "active",
    processing = "processing"
}
export interface backendInterface {
    createAppointment(input: CreateAppointmentInput): Promise<Appointment>;
    createService(input: CreateServiceInput): Promise<Service>;
    deleteAppointment(id: Id): Promise<boolean>;
    deleteService(id: Id): Promise<boolean>;
    getAppointment(id: Id): Promise<Appointment | null>;
    getAppointments(): Promise<Array<Appointment>>;
    getAppointmentsByClient(clientName: string): Promise<Array<Appointment>>;
    getAppointmentsByDateRange(startDate: ISODate, endDate: ISODate): Promise<Array<Appointment>>;
    getClientNames(): Promise<Array<string>>;
    getServices(): Promise<Array<Service>>;
    getSettings(): Promise<SettingsSnapshot>;
    updateAppointment(input: UpdateAppointmentInput): Promise<Appointment | null>;
    updateService(input: UpdateServiceInput): Promise<Service | null>;
    updateSettings(input: UpdateSettingsInput): Promise<void>;
}
import type { Appointment as _Appointment, CreateAppointmentInput as _CreateAppointmentInput, CreateServiceInput as _CreateServiceInput, HHmm as _HHmm, ISODate as _ISODate, Id as _Id, PhaseDef as _PhaseDef, PhaseInstance as _PhaseInstance, PhaseType as _PhaseType, Service as _Service, UpdateAppointmentInput as _UpdateAppointmentInput, UpdateServiceInput as _UpdateServiceInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAppointment(arg0: CreateAppointmentInput): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_CreateAppointmentInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Appointment_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_CreateAppointmentInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Appointment_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createService(arg0: CreateServiceInput): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_CreateServiceInput_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Service_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_CreateServiceInput_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Service_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAppointment(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteService(arg0: Id): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAppointment(arg0: Id): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByClient(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByClient(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByClient(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByDateRange(arg0: ISODate, arg1: ISODate): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDateRange(arg0, arg1);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDateRange(arg0, arg1);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientNames();
            return result;
        }
    }
    async getServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServices();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServices();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<SettingsSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async updateAppointment(arg0: UpdateAppointmentInput): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(to_candid_UpdateAppointmentInput_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(to_candid_UpdateAppointmentInput_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateService(arg0: UpdateServiceInput): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(to_candid_UpdateServiceInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(to_candid_UpdateServiceInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: UpdateSettingsInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_Appointment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PhaseDef_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhaseDef): PhaseDef {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PhaseInstance_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhaseInstance): PhaseInstance {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PhaseType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhaseType): PhaseType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_PhaseInstance>]): Array<PhaseInstance> | null {
    return value.length === 0 ? null : from_candid_vec_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    phaseLabel: string;
    durationMinutes: bigint;
    phaseType: _PhaseType;
}): {
    phaseLabel: string;
    durationMinutes: bigint;
    phaseType: PhaseType;
} {
    return {
        phaseLabel: value.phaseLabel,
        durationMinutes: value.durationMinutes,
        phaseType: from_candid_PhaseType_n15(_uploadFile, _downloadFile, value.phaseType)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel: [] | [string];
    phases: Array<_PhaseDef>;
}): {
    id: Id;
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel?: string;
    phases: Array<PhaseDef>;
} {
    return {
        id: value.id,
        name: value.name,
        isMultiPhase: value.isMultiPhase,
        colorHex: value.colorHex,
        price: value.price,
        finishingLabel: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.finishingLabel)),
        phases: from_candid_vec_n23(_uploadFile, _downloadFile, value.phases)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    startTime: _HHmm;
    clientName: string;
    date: _ISODate;
    durationMinutes: bigint;
    notes: [] | [string];
    serviceId: _Id;
    phone: [] | [string];
    price: number;
    phases: [] | [Array<_PhaseInstance>];
}): {
    id: Id;
    startTime: HHmm;
    clientName: string;
    date: ISODate;
    durationMinutes: bigint;
    notes?: string;
    serviceId: Id;
    phone?: string;
    price: number;
    phases?: Array<PhaseInstance>;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        clientName: value.clientName,
        date: value.date,
        durationMinutes: value.durationMinutes,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        serviceId: value.serviceId,
        phone: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.phone)),
        price: value.price,
        phases: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.phases))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    processing: null;
}): PhaseType {
    return "active" in value ? PhaseType.active : "processing" in value ? PhaseType.processing : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhaseInstance>): Array<PhaseInstance> {
    return value.map((x)=>from_candid_PhaseInstance_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhaseDef>): Array<PhaseDef> {
    return value.map((x)=>from_candid_PhaseDef_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n21(_uploadFile, _downloadFile, x));
}
function to_candid_CreateAppointmentInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAppointmentInput): _CreateAppointmentInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateServiceInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateServiceInput): _CreateServiceInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PhaseDef_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhaseDef): _PhaseDef {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_PhaseInstance_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhaseInstance): _PhaseInstance {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_PhaseType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhaseType): _PhaseType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateAppointmentInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateAppointmentInput): _UpdateAppointmentInput {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateServiceInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateServiceInput): _UpdateServiceInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel?: string;
    phases: Array<PhaseDef>;
}): {
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel: [] | [string];
    phases: Array<_PhaseDef>;
} {
    return {
        name: value.name,
        isMultiPhase: value.isMultiPhase,
        colorHex: value.colorHex,
        price: value.price,
        finishingLabel: value.finishingLabel ? candid_some(value.finishingLabel) : candid_none(),
        phases: to_candid_vec_n19(_uploadFile, _downloadFile, value.phases)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: HHmm;
    clientName: string;
    date: ISODate;
    durationMinutes: bigint;
    notes?: string;
    serviceId: Id;
    phone?: string;
    price: number;
    phases?: Array<PhaseInstance>;
}): {
    startTime: _HHmm;
    clientName: string;
    date: _ISODate;
    durationMinutes: bigint;
    notes: [] | [string];
    serviceId: _Id;
    phone: [] | [string];
    price: number;
    phases: [] | [Array<_PhaseInstance>];
} {
    return {
        startTime: value.startTime,
        clientName: value.clientName,
        date: value.date,
        durationMinutes: value.durationMinutes,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        serviceId: value.serviceId,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        price: value.price,
        phases: value.phases ? candid_some(to_candid_vec_n3(_uploadFile, _downloadFile, value.phases)) : candid_none()
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Id;
    startTime: HHmm;
    clientName: string;
    date: ISODate;
    durationMinutes: bigint;
    notes?: string;
    serviceId: Id;
    phone?: string;
    price: number;
    phases?: Array<PhaseInstance>;
}): {
    id: _Id;
    startTime: _HHmm;
    clientName: string;
    date: _ISODate;
    durationMinutes: bigint;
    notes: [] | [string];
    serviceId: _Id;
    phone: [] | [string];
    price: number;
    phases: [] | [Array<_PhaseInstance>];
} {
    return {
        id: value.id,
        startTime: value.startTime,
        clientName: value.clientName,
        date: value.date,
        durationMinutes: value.durationMinutes,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        serviceId: value.serviceId,
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        price: value.price,
        phases: value.phases ? candid_some(to_candid_vec_n3(_uploadFile, _downloadFile, value.phases)) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Id;
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel?: string;
    phases: Array<PhaseDef>;
}): {
    id: _Id;
    name: string;
    isMultiPhase: boolean;
    colorHex: string;
    price: number;
    finishingLabel: [] | [string];
    phases: Array<_PhaseDef>;
} {
    return {
        id: value.id,
        name: value.name,
        isMultiPhase: value.isMultiPhase,
        colorHex: value.colorHex,
        price: value.price,
        finishingLabel: value.finishingLabel ? candid_some(value.finishingLabel) : candid_none(),
        phases: to_candid_vec_n19(_uploadFile, _downloadFile, value.phases)
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    phaseLabel: string;
    durationMinutes: bigint;
    phaseType: PhaseType;
}): {
    phaseLabel: string;
    durationMinutes: bigint;
    phaseType: _PhaseType;
} {
    return {
        phaseLabel: value.phaseLabel,
        durationMinutes: value.durationMinutes,
        phaseType: to_candid_PhaseType_n6(_uploadFile, _downloadFile, value.phaseType)
    };
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhaseType): {
    active: null;
} | {
    processing: null;
} {
    return value == PhaseType.active ? {
        active: null
    } : value == PhaseType.processing ? {
        processing: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PhaseDef>): Array<_PhaseDef> {
    return value.map((x)=>to_candid_PhaseDef_n20(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PhaseInstance>): Array<_PhaseInstance> {
    return value.map((x)=>to_candid_PhaseInstance_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
